version: '3.4'

services:

  catalog_db:
    image: mongo

  catalog_api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.Api/Dockerfile

  basket_db:
    image: redis

  basket_api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket/Basket.Api/Dockerfile