version: '3.4'

services:

  um_catalog_db:
    container_name: um_catalog_db
    restart: always
    ports:
      - "27017:27017"

  um_catalog_api:
    container_name: um_catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CatalogDbSettings__Host=um_catalog_db
    depends_on:
      - um_catalog_db
    ports:
      - "6050:80"

  um_basket_db:
    container_name: um_basket_db
    restart: always
    ports:
      - "6379:6379"

  um_basket_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Redis=um_basket_db:6379
    depends_on:
      - um_basket_db
    ports:
      - "6051:80"