version: '3.4'

services:

  um_rabbit_mq:
    container_name: um_rabbit_mq
    image: rabbitmq:3-management-alpine

  um_product_db:
    container_name: um_product_db
    image: mongo

  um_basket_db:
    container_name: um_basket_db
    image: redis

  um_order_db:
    container_name: um_order_db
    image: mcr.microsoft.com/mssql/server:2017-latest

  um_product_api:
    container_name: um_product_api
    image: ${DOCKER_REGISTRY-}um_productapi
    build:
      context: .
      dockerfile: src/product/product.Api/Dockerfile

  um_basket_api:
    container_name: um_basket_api
    image: ${DOCKER_REGISTRY-}um_basket_api
    build:
      context: .
      dockerfile: src/Basket/Basket.Api/Dockerfile

  um_order_api:
    container_name: um_order_api
    image: ${DOCKER_REGISTRY-}um_order_api
    build:
      context: .
      dockerfile: src/Order/Order.Api/Dockerfile

  um_ocelot_api_gateway:
    container_name: um_ocelot_api_gateway
    image: ${DOCKER_REGISTRY-}um_ocelot_api_gateway
    build:
      context: .
      dockerfile: src/ApiGateway/Ocelot.ApiGateway/Dockerfile

