version: '3.4'

services:

  catalog_db:
    container_name: catalog_db
    restart: always
    ports:
      - "27017:27017"

  catalog_api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT="Production"
      - CatalogDbSettings__Host=catalog_db
    depends_on:
      - catalog_db
    ports:
      - "6050:80"

  basket_db:
    container_name: basket_db
    restart: always
    ports:
      - "6379:6379"

  basket_api:
    environment:
      - ASPNETCORE_ENVIRONMENT="Production"
      - "ConnectionStrings__Redis=basket_db:6379"
    depends_on:
      - basket_db
    ports:
      - "6051:80"