version: '3.4'

services:

  catalog_db:
    container_name: catalog_db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  

  catalog_api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CatalogDbSettings:ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalog_db
    ports:
      - "5010:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https/:/root/.aspnet/https/