version: '3.4'

services:

  um_rabbit_mq:
    container_name: um_rabbit_mq
    restart: always
    ports:
      - "4010:5672"
      - "4020:5672"

  um_catalog_db:
    container_name: um_catalog_db
    restart: always
    ports:
      - "27017:27017"

  um_catalog_api:
    container_name: um_catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CatalogDbSettings__Host=um_catalog_db
    depends_on:
      - um_catalog_db
    ports:
      - "6050:80"

  um_basket_db:
    container_name: um_basket_db
    restart: always
    ports:
      - "5002:6379"

  um_basket_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Redis=um_basket_db
      - EventBus__HostName=um_rabbit_mq
    depends_on:
      - um_basket_db
      - um_rabbit_mq
    ports:
      - "6051:80"