version: '3.4'

services:

  catalog_db:
    image: mongo

  catalog_db_mongo_express:
    image: mongo-express

  catalog_api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.Api/Dockerfile
